#!/usr/bin/env python3

# Copyright (c) 2019 Jacob WF House.
#
# This file is licensed under a MIT license.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

import re
import os
import datetime


POSTPATH = 'src/pages/blog/'
POSTTEMPLATE = '''\
---
path: '%(path)s'
title: '%(title)s'
date: '%(date)s'
published: false
image: ''
---


'''


def getSlug(title: str) -> str:
    slug = re.sub(
        r'\s', '-', ''.join(re.findall('[A-Za-z \-]', title)).lower())
    if input('Does %s look alright for a slug? (Y/n)' % (slug,)).lower() == 'n':
        slug = input('Enter a slug: ')
    return slug


def main() -> None:
    folder = os.getcwd() + '/' + POSTPATH
    title = input('Enter post title: ')
    slug = getSlug(title)
    while os.path.exists(folder + slug):
        print('That path exists. Please choose another.')
        slug = getSlug(slug + '-1')
    os.makedirs(folder + slug)
    with open(folder + slug + '/index.md', 'w') as mdFile:
        mdFile.write(POSTTEMPLATE % {
            'path': slug,
            'title': title,
            'date': datetime.datetime.now(),
        })
    print('You may now edit the file "%s."' % (folder + slug + '/index.md',))


if __name__ == '__main__':
    main()
